version: "3.9"
services:
  controller:
    build: .
    container_name: contoller
    hostname: controller
    ports:
      - "8000:8000"
      - "2026:22"
  web:
    build: .
    container_name: targety
    hostname: targety
    ports:
      - "5001:5000"
      - "2027:22"